### ISSUE TITLE
Image component

### ISSUE THREAD

**Issue by lucasaarcoverde** [vtex/admin-ui#17]
> ℹ️ This issue was originally opened by @ThaynanAndrey on **12 Nov 2020**

**Is your feature request related to a problem? Please describe.**
The element <img> can be a component with its properties and ensure all accessibility.  

Examples:
- The Image component requires the `figcaption` description to ensure accessibility;
- By default, the component is lazy loading to load data only when it's showed in screen;
- The Image component show a Skeleton while the bundle is loading, or the user can use the loading component to render.

**Describe the solution you'd like**
To this problem, I create a Image component like below:
```typescript
import { Box, Skeleton } from '@vtex/admin-ui'
import React, { FC, useState } from 'react'

interface Props {
  imageUrl: string
  alt: string
  height?: number
  width?: number
}

const Image: FC<Props> = ({ imageUrl, alt, height, width }) => {
  const [isImgLoaded, setImageLoaded] = useState(false)

  /*
   * It allows the <img> start the load, but don't show the image div.
   * If, instead this solution, use the `diplay=none`, the <img> element isn't loaded.
   */
  const imageHeight = isImgLoaded ? height : 0
  const imageWidth = isImgLoaded ? width : 0

  return (
    <Box element="figure" styles={{ minHeight: height, minWidth: width }}>
      {!isImgLoaded && <Skeleton styles={{ height, width }} />}
      <img
        src={imageUrl}
        alt={alt}
        loading="lazy"
        height={imageHeight}
        width={imageWidth}
        onLoad={() => {
          setImageLoaded(true)
        }}
      />
    </Box>
  )
}

export default Image
```

**Comment by davicostalf** [comment]
@lucasaarcoverde What Design would be needed for this component?

**Comment by lucasaarcoverde** [comment]
@davicostalf I'm not sure this issue makes sense for us now since it was opened in 2020. Can I close it?
