### ISSUE TITLE
TextArea label covered by input content

### ISSUE THREAD

**Issue by lucasaarcoverde** [vtex/admin-ui#21]
> This issue was originally opened by @luis-f-lins on **5 Mar 2021**

**Describe the bug**
On a TextArea with overflow (longer inputs), the text appears under the label, making it hard to be read. 

**To Reproduce**
- Create a Text Area
- Input a long text 
- Scroll up and down inside the text area

**Expected behavior**
Label can be still read even with longer inputs

**Screenshots**
![textarea](https://user-images.githubusercontent.com/5256673/110115447-da896000-7d94-11eb-8c06-2944cb408c6d.gif)

**Desktop (please complete the following information):**

- OS: macOS Big Sur
- Browser: Chrome
- Version: 88.0.4324.192

**Smartphone (please complete the following information):**
n/a 

**Additional context**
n/a

**Comment by davicostalf** [comment]
This was fixed since the label is no longer inside the input
