### ISSUE TITLE
NumericStepper: Passing csx

### ISSUE THREAD

**Issue by lucasaarcoverde** [vtex/admin-ui#22]
> This issue was originally opened by @lafray on **19 Mar 2021**

# Bug Report

- [x] I've read and understood the [Contributing guidelines](https://admin-ui.vercel.app/contributing/onboarding) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## What happened

When adding a style using the `csx` property to the `NumericStepper` component, the style it isn't applied properly.

## What I expected to happen

For example, when adding a margin to it I'd expect that margin is applied for the entire component, but this does not happen.

## Reproducing

- Admin-ui version in your `package.json`: `0.117.0
- Live link with error: https://codesandbox.io/s/amazing-hofstadter-8pd2k?file=/src/Root.tsx

## Attachments

![Captura de Tela 2022-02-08 às 15 40 48](https://user-images.githubusercontent.com/20579226/153054132-7346ac41-27ac-4905-a7b0-88013f921630.png)

**Comment by davicostalf** [comment]
@lafray Is this still happening on the reviewed component?

**Comment by lafray** [comment]
@davicostalf  this component not receive styles anymore, so, dont happens
