### ISSUE TITLE
Select component with smaller width

### ISSUE THREAD

**Issue by lucasaarcoverde** [vtex/admin-ui#23]
> This issue was originally opened by @mendesds on **23 Mar 2021**

**Describe the bug**
The Select component with block directive works ok to adjust the width according to parent div when the parent div is bigger than default Select width. But when the parent div is smaller, there is a fixed min-width that we can't control, even when there is space yet to decrease the width of component.

**To Reproduce**
It's possible to reproduce in docs, https://admin-ui-docs.vercel.app/form/select/#block, changing the card width to 200, for example:

![DeepinScreenshot_select-area_20210323131347](https://user-images.githubusercontent.com/6586829/112186119-9a710c80-8bdf-11eb-91ee-d0f5a9425f46.png)

**Expected behavior**
The component adapt to parent div when using block directive, even when the parent div be smaller than default select component.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome
- Version 88.0.4324.182 (Official Build) (64-bit)

**Additional context**

I already tried to use `width` and `maxWidth` on `csx` property directly on Select component, but both of them doesn't worked.

**Comment by davicostalf** [comment]
@mendesds Is this still happening on the reviewed component?

**Comment by davicostalf** [comment]
This component was reviewed, and this problem appears to have been fixed.
<img width="259" alt="image" src="https://user-images.githubusercontent.com/8797476/210566094-91b9c694-fe1a-4c8e-bdeb-a9f41fc7d93a.png">
