### ISSUE TITLE
Internationalize all rendered strings

### ISSUE THREAD

**Issue by lucasaarcoverde** [vtex/admin-ui#24]
> This issue was originally opened by @marcelovicentegc on **27 Apr 2021**

# Feature Request

- [x] I've read and understood the [Contributing guidelines](https://admin-ui.vercel.app/contributing/onboarding) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## Why is this suggestion important?

We have plenty of strings that are not localized. They are strings in English. We should be able to have strings translated in multiple languages on the admin-ui.

One idea that comes to my mind, is having a `i18n` prop on the components that have strings. We could set the language ISO of the component through the `i18n` prop

## Additional context

A good benchmark:
- https://material-ui.com/pt/guides/localization/

**Comment by davicostalf** [comment]
@marcelovicentegc We are already doing this, right? Should we close this issue?

**Comment by marcelovicentegc** [comment]
Absolutely, Davis! I'm closing this issue.

**Comment by marcelovicentegc** [comment]
Thanks for pointing out!
