### ISSUE TITLE
CORS error retrieving VTEX Trust font

### ISSUE THREAD

**Issue by lucasaarcoverde** [vtex/admin-ui#26]
> This issue was originally opened by @thayannevls on **1 Jun 2021**

**Describe the bug**

A CORS error is happening when trying to download the `VTEXTrust-Variable.woff2` font. 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://io.vtex.com.br/fonts/vtex-trust/VTEXTrust-Variable.woff2. (Reason: CORS request did not succeed).

downloadable font: download failed (font-family: "VTEXTrustVF" style:normal weight:400 stretch:100 src index:0): bad URI or cross-site access not allowed source: https://io.vtex.com.br/fonts/vtex-trust/VTEXTrust-Variable.woff2
```

This is a problem in browsers like Firefox, which immediately block the request and uses a fallback font.

**To Reproduce**

1. Go to any application using `@vtex/admin-ui`. E.g.: https://admin-ui-docs.vercel.app/
2. Open the console, and you will see the CORS error.

**Expected behavior**
No CORS error occurs, and the `VTEXTrust-Variable.woff2` font is used.

**Comment by davicostalf** [comment]
@lucasaarcoverde We've updated the font since this issue was opened. Can you check if this error is still occurring?

**Comment by davicostalf** [comment]
@lucasaarcoverde Is this still hapenning?

**Comment by lucasaarcoverde** [comment]
> @lucasaarcoverde Is this still hapenning?

I'm not sure, we didn't receive any report recently. I'll close for now
