### ISSUE TITLE
Select: Loading state

### ISSUE THREAD

**Issue by lucasaarcoverde** [vtex/admin-ui#27]
> This issue was originally opened by @rerissondaniel  on **11 Jun 2021**

**Is your feature request related to a problem? Please describe.**
I would like to show a spinner while the items of `Select` (and `FormikSelect`) are loading.

**Describe the solution you'd like**
A prop indicating that the component is loading or the possibility to pass the select icon.
Something like:
<img width="756" alt="Captura de Tela 2021-06-11 às 14 52 30" src="https://user-images.githubusercontent.com/4912690/121729363-c4421d00-cac4-11eb-91dc-74c456e8a4b6.png">

**Describe alternatives you've considered**
Currently we just leave the select disabled.

**Additional context**

**Comment by davicostalf** [comment]
Duplicated in #513
