### ISSUE TITLE
Tooltip: doesn't show when moving between buttons

### ISSUE THREAD

**Issue by lucasaarcoverde** [vtex/admin-ui#34]
> This issue was originally opened by @ThaynanAndrey on **21 Oct 2021**

# Bug Report

- [x] I've read and understood the [Contributing guidelines](https://admin-ui-docs.vercel.app/engineering/contributing/) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## What happened
Tooltip doesn't show when I move mouse between two neighboring buttons
As title says, you can see the problem in the screencast below.
https://user-images.githubusercontent.com/18720551/138339252-420f59f3-982a-4856-8da0-0b6eeb717613.mov

## What I expected to happen
The tooltip show in all buttons.

## Reproducing

- I implemented as the code below:
```jsx
<Flex>
 <Tooltip
      label={tooltip}
      baseId="table-view-option-id"
    >
      <Label csx={classContainer}>
        <Box
          as="input"
          type="radio"
          name="selectedOption"
          value={option.value}
          checked={isSelectedOption}
          csx={radioInputStyle}
          onChange={(e) => handleOption(e.target.value)}
          disabled={disabled}
        />
        {Icon && <Icon />}
        {option.label}
      </Label>
    </Tooltip>
 <Tooltip
      label={tooltip}
      baseId="table-view-option-id"
    >
      <Label csx={classContainer}>
        <Box
          as="input"
          type="radio"
          name="selectedOption"
          value={option.value}
          checked={isSelectedOption}
          csx={radioInputStyle}
          onChange={(e) => handleOption(e.target.value)}
          disabled={disabled}
        />
        {Icon && <Icon />}
        {option.label}
      </Label>
    </Tooltip>
</Flex>
```

**Comment by davicostalf** [comment]
@ThaynanAndrey Is this still happening in the current component?

**Comment by ThaynanAndrey** [comment]
@davicostalf, i'm not using the latest version of the tooltip. When I use, I'll give a new feedback 😄

**Comment by lucasaarcoverde** [comment]
It seems to be fixed: https://codesandbox.io/s/affectionate-meninsky-upggdv?file=/src/Root.tsx

I'll close this issue for now.
