### ISSUE TITLE
Menu: hideOnClick option blocks MenuItems from opening modals

### ISSUE THREAD

**Issue by lucasaarcoverde** [vtex/admin-ui#39]
> This issue was originally opened by @matheusps on **17 Nov 2021**

# Bug Report

- [x] I've read and understood the [Contributing guidelines](https://admin-ui-docs.vercel.app/engineering/contributing/) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## What happened

If the `hideOnClick` option is activated, the `Menu` users cannot open modals. https://codesandbox.io/s/prod-violet-y83lb?file=/src/App.js 

## What I expected to happen

The modal should open normally. When we remove it, it works https://codesandbox.io/s/nostalgic-driscoll-z6kb5?file=/src/App.js.

**Comment by davicostalf** [comment]
@lucasaarcoverde Is this still hapenning?

**Comment by lucasaarcoverde** [comment]
> @lucasaarcoverde Is this still happening?

@davicostalf I've just checked and it isn't

https://codesandbox.io/s/wonderful-bush-ygtp2k?file=/src/Root.tsx
