### ISSUE TITLE
Icon: Add IconArrowBendDownLeft

### ISSUE THREAD

**Issue by lafray** [vtex/admin-ui#42]
# Feature Request

- [x] I've read and understood the [Contributing guidelines](https://admin-ui.vercel.app/contributing/onboarding) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## Is this feature request related to an existing component? Please describe.

Add export in admin-ui to the icon IconArrowBendDownLeft in the phosphor-icons

## Why is this suggestion important?

It's necessary in this context, for example, (tag input)
![Captura de Tela 2022-02-08 às 18 23 26](https://user-images.githubusercontent.com/36760180/153078297-3653f88f-66d7-43b7-965c-aa1dd925fa4c.png)

**Comment by davicostalf** [comment]
@lafray Does the current Combobox component work for this scenario?
