### ISSUE TITLE
Modal: review

### ISSUE THREAD

**Issue by matheusps** [vtex/admin-ui#434]
Review the modal component according to the newest design specs.

- [ ] Design handoff
- [ ] API RFC
- [ ] Component implementation
- [ ] Test cases
- [ ] Documentation

**Comment by lucasaarcoverde** [comment]
I'm closing this issue since all of the items were done:
- Modal docs: https://github.com/vtex/admin-ui/pull/534
- Modal review: https://github.com/vtex/admin-ui/pull/452
