### ISSUE TITLE
Search placeholder

### ISSUE THREAD

**Issue by beatrizmilhomem** [vtex/admin-ui#455]
Since we got a lot of feedback, including from [clients](https://vtex.slack.com/archives/D03EZ4M5XST/p1667935377545839), related to the **Search placeholder** be missing instructions about what can be searched, **we decided to make it customizable**.

* Component will have a default placeholder Search
* Placeholder can be customizable

**Comment by davicostalf** [comment]
@lucasaarcoverde Can we mark this as done?

**Comment by marcelovicentegc** [comment]
I'm closing this issue since this was released on [@vtex/admin-ui@0.135.0](https://github.com/vtex/admin-ui/releases/tag/%40vtex%2Fadmin-ui%400.135.0)
