### ISSUE TITLE
Date Picker: Week starting on the wrong day

### ISSUE THREAD

**Issue by matheusps** [vtex/admin-ui#456]
# Bug Report

## What happened

For clients using Admin UI in brazil or other time zones, the week loads on the correct day. This is not true for clients using in the UK. The week is starting on a wrong day, causing a shift  (day-weekday). 

## What I expected to happen

It should be correct for users on all timezones. 

### For UK users:

<img width="772" alt="Screen Shot 2022-11-10 at 15 39 23" src="https://user-images.githubusercontent.com/6964311/201179173-dfca61b5-afb8-4df8-bb99-4d126bb01b96.png">

### For BR users:

<img width="856" alt="Screen Shot 2022-11-10 at 15 39 58" src="https://user-images.githubusercontent.com/6964311/201179293-7c54acf7-424f-496d-8157-c8110ce14e19.png">

**Comment by davicostalf** [comment]
@matheusps @lucasaarcoverde Is this issue solved?

**Comment by lucasaarcoverde** [comment]
I believe it was fixed on this PR: https://github.com/vtex/admin-ui/pull/493

**Comment by lucasaarcoverde** [comment]
Solved
