### ISSUE TITLE
Z-index confit when has tooltip in modal

### ISSUE THREAD

**Issue by lafray** [vtex/admin-ui#464]
# Bug Report

- [x] I've read and understood the [Contributing guidelines](https://admin-ui.vercel.app/contributing/onboarding) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## What happened

When there is a tooltip in a modal, the z index of the tooltip causes it to be rendered behind the modal, making it impossible to see it. The way this tooltip component's API is, it's not possible to change its z-index, and it's not possible to do any local checks.

## What I expected to happen

- That the z-index adapts to the context in which it is being placed
- Or that it has a value that guarantees all scenarios
- And for the time being this does not happen, that we can at least make the manual set of a z-index

## Reproducing

- [Click to open the modal end make hoover in tooltip](https://codesandbox.io/s/z-index-tooltip-8ix121?file=/src/App.tsx)

**Comment by lafray** [comment]
@matheusps

**Comment by davicostalf** [comment]
Duplicated #20
