### ISSUE TITLE
Spacing tokens: design docs

### ISSUE THREAD

**Issue by beatrizmilhomem** [vtex/admin-ui#469]
Add to our documentation website the space tokens design documentation.

https://www.notion.so/vtexhandbook/Spacing-Tokens-c346971cbca540cbb6e3ed4a02701cbe

**Comment by beatrizmilhomem** [comment]
@davicostalf @eoqmoreno here's a proposal for the spacing tokens documentation for you to give feedback:
https://www.notion.so/vtexhandbook/Spacing-Tokens-c346971cbca540cbb6e3ed4a02701cbe#be9b4eb25d3641519fc84db957f8c981
* Added some image suggestions according to the examples
* @davicostalf we talked about adding some questions in the end for some applications, but I think the examples in the table can be enough for designers (I tried to gather both the scenarios and examples you have listed before)

**Comment by davicostalf** [comment]
Nice! Left some comments in the Notion page.

**Comment by beatrizmilhomem** [comment]
@davicostalf @eoqmoreno thanks for your comments! I answered some of them, please check.
I've made some small changes to the content and a proposal for the images on [Figma](https://www.figma.com/file/wZhi9a069zCU5lMJq4Gf1r/Beyond-Components?node-id=743%3A320817&t=Ewpz5gn1TtB4ZM5q-4). I expect your feedback on that too! ✨

**Comment by davicostalf** [comment]
@beatrizmilhomem Took another look and left some more comments 😉

**Comment by beatrizmilhomem** [comment]
Documentation was sent to the education team.

**Comment by beatrizmilhomem** [comment]
@davicostalf Júlia shared the reviewed document, please take a look https://docs.google.com/document/d/1rI3lbR5ypewZ5sKGALCGLD33YPkaCdIox3whR3m4TWM/edit?usp=sharing
