### ISSUE TITLE
Designing with Admin UI

### ISSUE THREAD

**Issue by beatrizmilhomem** [vtex/admin-ui#473]
Document why and how designers should use Admin UI
https://www.notion.so/vtexhandbook/Why-and-how-designers-should-use-Admin-UI-4e9f99bb6f6e43988c237695f649e9eb

**Comment by beatrizmilhomem** [comment]
@davicostalf I made a [first version of the document](https://www.notion.so/vtexhandbook/Designing-with-Admin-UI-4e9f99bb6f6e43988c237695f649e9eb), let me know what you think

**Comment by davicostalf** [comment]
Looking good, Bia! Very nice to have these ideas finally consolidated somewhere. Left more comments in the Notion Page.

**Comment by davicostalf** [comment]
@beatrizmilhomem What do you think of using just "Designing" as the title, instead of "Designing with Admin UI"?
Since we only have one page so far, maybe it should be in the introduction section.
