### ISSUE TITLE
Replace icon in thumbnail for image [Page Header]

### ISSUE THREAD

**Issue by eoqmoreno** [vtex/admin-ui#479]
Replace icon that represent name abbreviation in image placeholder

**Comment by eoqmoreno** [comment]
- I took the image placeholder from the table cell (image + name) which allows you to replace the image.
- I changed the size of the icon from 24x24 to 20x20 to match the other elements of the page header.
- I added border in hover state to improve image visualization on tertiary background.

Link to frame: https://www.figma.com/file/sepBhrHViUHyrTnktkuHaW/Admin-UI-%E2%80%93-Components?node-id=6532%3A416740&t=wtYOPYeHoOnwkgEH-1

**Comment by davicostalf** [comment]
- What is the scenario where the rounded one would be used?
- I would call this a Thumbnail, since Avatars represent people.

**Comment by eoqmoreno** [comment]
Change should be in the Page Header and not in the Top Bar.

- [ ] Returned the user icon on the top bar to default.

Export placeholder with icon and apply it as an image.

- [ ] I took the same one from the table to reuse.

Icon should be fg.disabled.

- [ ] When I got the same image from the table, the icon color was the same fg.disabled
