### ISSUE TITLE
Hide shadow in default state [Menu]

### ISSUE THREAD

**Issue by eoqmoreno** [vtex/admin-ui#483]
Hide shadow when menu is in default state. The shadow has been updated in the main component, but it needs to be updated in the component that uses this component

**Comment by eoqmoreno** [comment]
This issue was resolved when we revised the Menu component, but on some components (page, card and table) it was not updated.

To resolve it, it was necessary to update the component instance in components that have a nested Menu.

**Comment by davicostalf** [comment]
I also saw this on the filters in the table
