### ISSUE TITLE
Search: Param onChange when useSearchState is not returned by getInputProps

### ISSUE THREAD

**Issue by viniciuslagedo** [vtex/admin-ui#572]
# Bug Report

- [x] I've read and understood the [Contributing guidelines](https://admin-ui.vercel.app/contributing/onboarding) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## What happened
When I use the onChange param to pass a custom event to the useSearchState hook, that event is not returned by getInputProps

## What I expected to happen

The custom onChange event should be returned on getInputProps.

## Reproducing

- Admin-ui version in your `package.json`: 0.134.1
- Live link with error: https://codesandbox.io/s/vigorous-kare-9wp8pd

**Comment by lucasaarcoverde** [comment]
Good catch @viniciuslagedo! It's not returning indeed, we'll fix it
