### ISSUE TITLE
Modal: click events propagate to elements behind component

### ISSUE THREAD

**Issue by lafray** [vtex/admin-ui#577]
# Bug Report

- [x] I've read and understood the [Contributing guidelines](https://admin-ui.vercel.app/contributing/onboarding) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## What happened

- Event propagation to elements behind the modal

## What I expected to happen

When modal is open, not propagate click events to elements behind him

## Reproducing

- Admin-ui version in your `package.json`: 0.135.0
- Live link with error: https://codesandbox.io/s/event-propagation-lw25mh?file=/src/App.tsx

Steps to reproduce:

1. try open modal
2. click any where in modal

**Comment by davicostalf** [comment]
@lafray is this still happening in the latest version?

**Comment by lafray** [comment]
No. It has been fixed
