### ISSUE TITLE
Customization of radio style using an external component

### ISSUE THREAD

**Issue by AndersonSMed** [vtex/admin-ui#598]
# Feature Request

- [x] I've searched for any related issues and avoided creating a duplicate issue.

## Is this feature request related to an existing component? Please describe.

I would like to have some way to customize the Radio component so I could support different styles, like using each radio as a box (like in the picture below).

<img width="744" alt="image" src="https://user-images.githubusercontent.com/15149071/218183993-3537059b-5ebb-4073-b078-cda05aa32ec1.png">

## Do you have a suggestion for a new component?

Maybe a new prop that will receive a component that will replace the default circle that's used by the radio, and this component could receive some injected context so it could show itself as disabled, focused and so on.

## Why is this suggestion important?

It's important so I can use this component in some new pages regarding the new Catalog pages that are under construction.

**Comment by davicostalf** [comment]
Duplicates #527
