### ISSUE TITLE
Page Header z-index is higher then Modal's (backdrop included) z-index

### ISSUE THREAD

**Issue by marcelovicentegc** [vtex/admin-ui#604]
# Bug Report

- [x] I've read and understood the [Contributing guidelines](https://admin-ui.vercel.app/contributing/onboarding) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## What happened

<img width="1253" alt="image (1)" src="https://user-images.githubusercontent.com/33183880/219128689-02158b73-18eb-49c3-a1ac-5b5d50e280d3.png">
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/33183880/219128697-6c9a5ad1-1394-4ada-a02a-95f4600f2029.png">

Source: https://vtex.slack.com/archives/C01DVTFA4VA/p1676462762087559?thread_ts=1676462616.884739&cid=C01DVTFA4VA
cc @vlaux 

## What I expected to happen

- The modal's backdrop z-index must be higher than the Page Header's.

**Comment by davicostalf** [comment]
@marcelovicentegc Was this fixed in the last release?

**Comment by marcelovicentegc** [comment]
Good catch, @davicostalf. I'm closing this issue since it was fixed in [@vtex/admin-ui@0.136.0](https://github.com/vtex/admin-ui/releases/tag/%40vtex%2Fadmin-ui%400.136.0)
