### ISSUE TITLE
Combobox's label z-index is higher then Modal's z-index

### ISSUE THREAD

**Issue by marcelovicentegc** [vtex/admin-ui#605]
# Bug Report

- [x] I've read and understood the [Contributing guidelines](https://admin-ui.vercel.app/contributing/onboarding) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## What happened

<img width="406" alt="image (3)" src="https://user-images.githubusercontent.com/33183880/219129369-cff2aa2b-c95b-4af0-b1a6-cff5938a1994.png">
<img width="996" alt="image (2)" src="https://user-images.githubusercontent.com/33183880/219129374-f6f5d69d-6712-4f99-b400-562de9aefd3a.png">

Source: https://vtex.slack.com/archives/C01DVTFA4VA/p1676462881962679?thread_ts=1676462616.884739&cid=C01DVTFA4VA
cc @vlaux 

## What I expected to happen

Combobox's label z-index should be lower than any of Modal's z-index.

**Comment by davicostalf** [comment]
@marcelovicentegc Was this fixed in the last release?

**Comment by marcelovicentegc** [comment]
Good catch, @davicostalf. I'm closing this issue since it was fixed in [@vtex/admin-ui@0.136.0](https://github.com/vtex/admin-ui/releases/tag/%40vtex%2Fadmin-ui%400.136.0)
