### ISSUE TITLE
Make the apply button optional in the `FilterBar` component.

### ISSUE THREAD

**Issue by hiagolcm** [vtex/admin-ui#67]
# Feature Request

- [x] I've read and understood the [Contributing guidelines](https://admin-ui.vercel.app/contributing/onboarding) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## Is this feature request related to an existing component? Please describe.

[`FilterBar` has the `onApply`parameter ](https://admin-ui.vercel.app/components/filter-bar#parameters), but it would be nice to have an `onChange` parameter too. This way the `Apply` button will be optional

## Why is this suggestion important?

In some cases, the Apply button is not needed and can make the UI confusing. [Here](https://master--storecomponents.myvtex.com/admin/app/search/custom-result/create/) is an example.

This is an old component based on the `styleguide`. We are trying to migrate it to the `admin-ui`.  Turns out it looks like the `FilterBar` component, so we decided to use it.

The `FilterBar` will be inside the form. The form has the `save` button which makes the apply button unnecessary.

How it is (`styleguide`)
![before](https://user-images.githubusercontent.com/40380674/155216149-14cb4789-4496-441f-9438-6574272f13dd.gif)

How I would like it to be(`Filterbar(admin-ui)`)
![after](https://user-images.githubusercontent.com/40380674/155216206-af666632-17b0-43b8-a1d0-a781bfe1cbf0.gif)

**Comment by davicostalf** [comment]
The Filter Bar component is deprecated
