### ISSUE TITLE
Menu: pressing arrow doesn't open the menu

### ISSUE THREAD

**Issue by marcelovicentegc** [vtex/admin-ui#679]
# Bug Report

- [x] I've read and understood the [Contributing guidelines](https://admin-ui.vercel.app/contributing/onboarding) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## What happened

This:

https://user-images.githubusercontent.com/33183880/230950675-9f47fe4e-95a7-4fca-b190-beb2a66a8042.mov

## What I expected to happen

I expected the menu button's arrow to open the menu.

**Comment by davicostalf** [comment]
#678 duplicates this
