### ISSUE TITLE
Number Input: down/up buttons submit form

### ISSUE THREAD

**Issue by lafray** [vtex/admin-ui#703]
# Bug Report

- [x] I've read and understood the [Contributing guidelines](https://admin-ui.vercel.app/contributing/onboarding) and have done my best effort to follow them.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

## What happened

With the new version of admin-ui (0.136.0) the buttons voted to submit by default, because of this the up/down button of the number imput is submitting the form

## What I expected to happen

Clicking the up/down button should not submit the form

## Reproducing

- open https://codesandbox.io/s/form-validation-number-input-q9ps9m?file=/src/App.tsx
- click in up or down buttons

**Comment by davicostalf** [comment]
@lafray This issue was already solved, right?

**Comment by lafray** [comment]
Yes, in 0.136.1 version
